version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your-super-secret-key-change-in-production-env
    depends_on:
      - auth-service
      - catalog-service
      - order-service
      - payment-service
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - JWT_SECRET=your-super-secret-key-change-in-production-env
      - DATABASE_URL=jdbc:postgresql://ep-late-paper-a8qs55xj-pooler.eastus2.azure.neon.tech:5432/neondb?sslmode=require&channel_binding=require
      - DATABASE_USER=neondb_owner
      - DATABASE_PASSWORD=npg_jCnufk2oOc3Y
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - JWT_SECRET=your-super-secret-key-change-in-production-env
      - SERVICE_AUTH_URL=http://auth-service:8081
      - DATABASE_URL=jdbc:postgresql://ep-late-paper-a8qs55xj-pooler.eastus2.azure.neon.tech:5432/neondb?sslmode=require&channel_binding=require
      - DATABASE_USER=neondb_owner
      - DATABASE_PASSWORD=npg_jCnufk2oOc3Y
    depends_on:
      - auth-service
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - JWT_SECRET=your-super-secret-key-change-in-production-env
      - SERVICE_AUTH_URL=http://auth-service:8081
      - SERVICE_CATALOG_URL=http://catalog-service:8082
      - SERVICE_PAYMENT_URL=http://payment-service:8084
      - DATABASE_URL=jdbc:postgresql://ep-late-paper-a8qs55xj-pooler.eastus2.azure.neon.tech:5432/neondb?sslmode=require&channel_binding=require
      - DATABASE_USER=neondb_owner
      - DATABASE_PASSWORD=npg_jCnufk2oOc3Y
    depends_on:
      - auth-service
      - catalog-service
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - JWT_SECRET=your-super-secret-key-change-in-production-env
      - SERVICE_AUTH_URL=http://auth-service:8081
      - SERVICE_ORDER_URL=http://order-service:8083
      - DATABASE_URL=jdbc:postgresql://ep-late-paper-a8qs55xj-pooler.eastus2.azure.neon.tech:5432/neondb?sslmode=require&channel_binding=require
      - DATABASE_USER=neondb_owner
      - DATABASE_PASSWORD=npg_jCnufk2oOc3Y
    depends_on:
      - auth-service
      - order-service
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  microservices-network:
    driver: bridge
